name: CI

on:
  push:
    branches:
      - main
      - "releases/*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@v2
        with:
          command: test
          json: false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run tests
        run: npm test

      - name: Upload Snyk test results as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: snyk-results
          path: snyk-results.json

      - name: Upload test results as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.xml
